# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool: 'Default'

variables:
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  inputs:
        targetType: 'inline'
        script: '# Write your powershell commands here.
          
          Write-Host "$(build.sourcesDirectory)"
          
          # Use the environment variables input below to pass secret variables to this script.'